sudo: required
dist: zesty
language: c++

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libsqlite3-dev qt5-default qtquickcontrols2-5-dev qml-module-qtquick-controls2 qml-module-qtquick-templates2 qtdeclarative5-private-dev
  - sudo apt-get install -qq gnupg1 || sudo apt-get install -qq gnupg

script:
  - qmake -v
  - qmake
  - make

