sudo: required
dist: xenial
language: c++

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libsqlite3-dev qt5-default qtdeclarative5-private-dev
# qtquickcontrols2-5-dev qml-module-qtquick-controls2 qml-module-qtquick-templates2
  - sudo apt-get install -qq gnupg1 || sudo apt-get install -qq gnupg

script:
  - qmake -v
  - qmake
  - make

